# 水箱PID入口控制 - 通用配置文件
# 重构后的水箱PID入口控制示例

metadata:
  name: "水箱PID入口控制"
  description: "重构后的水箱PID入口控制示例"
  category: "watertank_refactored"
  version: "1.0"

simulation:
  time:
    start: 0.0
    end: 300.0
    step: 1.0
  solver:
    type: "euler"
    tolerance: 1e-6

system:
  components:
    - name: "watertank"
      type: "WaterTank"
      config:
        capacity: 1000.0
        initial_level: 40.0
        area: 100.0
    - name: "inlet_valve"
      type: "Valve"
      config:
        max_flow: 50.0
        initial_position: 0.5
        
control:
  enabled: true
  controllers:
    - name: "level_controller"
      type: "PID"
      input: "watertank.water_level"
      output: "inlet_valve.position"
      setpoint: 70.0
      parameters:
        kp: 2.0
        ki: 0.1
        kd: 0.5
        
monitoring:
  enabled: true
  variables:
    - "watertank.water_level"
    - "watertank.volume"
    - "inlet_valve.flow_rate"
    - "level_controller.error"
    - "level_controller.output"
    
logging:
  level: "INFO"
  output_file: "pid_control.log"