# Multi-Agent System (MAS) Event-Driven Simulation Configuration
# This configuration demonstrates the multi-agent system architecture where components
# are fully decoupled and communicate only via a MessageBus

simulation:
  duration: 60000   # seconds - 10分钟仿真时间 (与run_mas_simulation.py一致)
  dt: 0.5         # time step - 0.5秒时间步长 (与run_mas_simulation.py一致)

# Communication topics for message bus
communication:
  topics:
    digital_twin_state: 'dt_state'
    sensor_data: 'sensor_readings'
    control_actions: 'control_cmds'
    reservoir_state: "state.reservoir.level"
    gate_action: "action.gate.opening"

components:
  reservoir_1:
    type: Reservoir
    initial_state:
      volume: 21000000      # m³ - 与run_mas_simulation.py一致
      water_level: 14.0     # m
    parameters:
      surface_area: 1500000 # m² (1.5e6)
      storage_curve:
        - [0, 0]
        - [21000000, 14.0]
        - [30000000, 20]

  gate_1:
    type: Gate
    initial_state:
      opening: 0.1          # Initial opening (0-1)
    parameters:
      max_rate_of_change: 0.5  # 与run_mas_simulation.py一致
      discharge_coefficient: 0.6  # 与run_mas_simulation.py一致
      width: 10             # m - 与run_mas_simulation.py一致
      max_opening: 1.0
    message_bus:
      enabled: true
      action_topic: "action.gate.opening"

# Agent configuration
agents:
  twin_agent_reservoir_1:
    type: DigitalTwinAgent
    agent_id: "twin_agent_reservoir_1"
    simulated_object: "reservoir_1"
    message_bus:
      state_topic: "state.reservoir.level"

  control_agent_gate_1:
    type: UnifiedGateControlAgent
    agent_id: "control_agent_gate_1"
    controller:
      type: SmartPIDController
      parameters:
        Kp: 5.0              # 适中的比例增益
        Ki: 0.5              # 适中的积分增益
        Kd: 0.0              # 禁用微分，避免噪声
        setpoint: 12.0        # Target water level (m)
        min_output: 0.0
        max_output: 1.0       # Same as gate max_opening
        windup_limit: 0.5     # 积分抗饱和限制
        filter_constant: 0.1  # 微分滤波时间常数
    message_bus:
      observation_topic: "state.reservoir.level"
      observation_key: "water_level"
      action_topic: "action.gate.opening"

# Physical connections between components
connections:
  - from: "reservoir_1"
    to: "gate_1"

debug:
  enabled: true
  log_interval: 5

# Analysis and output settings
analysis:
  final_state_report: true
  target_water_level: 12.0
  
visualization:
  enabled: true
  save_path: "03_mas_results.png"
  plots:
    - title: "Reservoir Water Level vs Time"
      x_data: "time"
      y_data: "reservoir_water_level"
      ylabel: "Water Level (m)"
      target_line: 12.0
    - title: "Gate Opening vs Time"
      x_data: "time"
      y_data: "gate_opening"
      ylabel: "Gate Opening (0-1)"
    - title: "Reservoir Volume vs Time"
      x_data: "time"
      y_data: "reservoir_volume"
      ylabel: "Volume (m³)"