components:
- class: Reservoir
  id: upstream_reservoir
  initial_state:
    water_level: 10.0
  parameters:
    area: 10000.0
    inflow: 50.0
- class: Gate
  id: gate_1
  initial_state:
    opening: 0.5
  parameters:
    discharge_coefficient: 0.8
    width: 5.0
- class: UnifiedCanal
  id: canal_1
  initial_state:
    water_level: 5.0
  parameters:
    delay: 300
    gain: 0.001
    model_type: integral_delay
- class: UnifiedCanal
  id: canal_2
  initial_state:
    water_level: 4.5
  parameters:
    delay: 600
    gain: 0.001
    model_type: integral_delay
- class: Gate
  id: gate_2
  initial_state:
    opening: 0.5
  parameters:
    discharge_coefficient: 0.8
    width: 5.0
project:
  category: canal_model
  description: 通用配置文件，用于 canal_model/canal_pid_control 示例
  name: canal_pid_control
  version: '1.0'
runtime:
  logging_level: INFO
  mode: simulation
simulation:
  dt: 10
  duration: 7200
