# Simulation Configuration
metadata:
  run_with: run_scenario.py
  example_type: yaml_config
  description: Centralized emergency override control example

simulation:
  duration: 200  # Simulation total time in seconds
  dt: 1.0        # Simulation time step in seconds
