components:
- class: Reservoir
  id: main_reservoir
  initial_state:
    water_level: 98.0
  parameters:
    area: 1000.0
    inflow: 100.0
    storage_curve:
    - - 0
      - 0
    - - 100000
      - 100
- class: Gate
  id: flood_gate
  initial_state:
    opening: 0.1
  parameters:
    discharge_coefficient: 0.8
    width: 5.0
metadata:
  description: Centralized emergency override control example
  example_type: yaml_config
  run_with: run_scenario.py
project:
  category: agent_based
  description: 通用配置文件，用于 agent_based/06_centralized_emergency_override 示例
  name: 06_centralized_emergency_override
  version: '1.0'
runtime:
  logging_level: INFO
  mode: simulation
simulation:
  dt: 1.0
  duration: 200
