analysis:
  performance_metrics:
    channel_control:
      stability_threshold: 10000
      steady_state_error_threshold: 50000
    reservoir_control:
      stability_threshold: 0.1
      steady_state_error_threshold: 0.5
  visualization:
    enabled: true
    output_file: 02_multi_component_results.png
    plots:
    - title: Reservoir Water Level Control
      type: reservoir_level
    - title: Channel Volume Control
      type: channel_volume
    - title: Gate 1 Opening (Reservoir Control)
      type: gate1_opening
    - title: Gate 2 Opening (Channel Control)
      type: gate2_opening
components:
  channel_1:
    initial_state:
      volume: 500000
    parameters:
      k: 0.0001
    type: RiverChannel
  gate_1:
    initial_state:
      opening: 0.25
    parameters:
      discharge_coefficient: 0.8
      width: 12
    type: Gate
  gate_2:
    initial_state:
      opening: 0.5
    parameters:
      discharge_coefficient: 0.7
      width: 10
    type: Gate
  reservoir_1:
    initial_state:
      volume: 15000000
      water_level: 15.0
    parameters:
      storage_curve:
      - - 0
        - 0
      - - 30000000
        - 30
      surface_area: 1000000
    type: Reservoir
connections:
- from: reservoir_1
  to: gate_1
- from: gate_1
  to: channel_1
- from: channel_1
  to: gate_2
controllers:
  chan_vol_ctrl:
    controlled_component: gate_2
    description: Controls channel volume by adjusting Gate 2
    observation_key: volume
    observed_component: channel_1
    parameters:
      Kd: -1.0e-06
      Ki: -1.0e-07
      Kp: -1.0e-05
      max_output: 1.0
      min_output: 0.0
      setpoint: 400000
    type: PIDController
  res_level_ctrl:
    controlled_component: gate_1
    description: Controls reservoir water level by adjusting Gate 1
    observation_key: water_level
    observed_component: reservoir_1
    parameters:
      Kd: -0.05
      Ki: -0.01
      Kp: -0.2
      max_output: 1.0
      min_output: 0.0
      setpoint: 18.0
    type: PIDController
project:
  category: non_agent_based
  description: 通用配置文件，用于 non_agent_based/02_multi_component_systems 示例
  name: 02_multi_component_systems
  version: '1.0'
runtime:
  logging_level: INFO
  mode: simulation
simulation:
  dt: 1.0
  duration: 500
