# Mission Example 5.4 - 闸门调度表计算配置

optimization:
  gate_count: 5
  flow_range:
    min_cms: 0
    max_cms: 1000
    step_cms: 50
  
  head_range:
    min_m: 5
    max_m: 25
    step_m: 2

safety_rules:
  symmetric_opening: true  # 对称开启规则
  max_opening_rate: 0.1    # 最大开启速率 (m/s)

output:
  table_filename: "gate_flow_allocation_table.csv"
  save_path: "../data/"

# 通用配置
general:
  validation:
    enabled: true
  
  debug:
    enabled: true
    log_level: "INFO"
    verbose: false
  
  performance:
    track_timing: true