# Mission Example 2 - Config 2.1 通用配置文件
# 现地闭环控制系统配置

# ============================================================
# 仿真配置
# ============================================================
simulation:
  name: "现地闭环控制系统仿真"
  description: "Example 2.1 - 验证一个由现地PID智能体独立工作的完整闭环控制系统"
  version: "1.0.0"
  
  # 时间设置
  time:
    end_time: 2000.0      # 仿真持续时间 (秒)
    time_step: 10.0       # 时间步长 (秒)
    output_interval: 100.0  # 输出间隔 (秒)
    
  # 求解器配置
  solver:
    method: "pid"         # PID控制求解方法
    tolerance: 1e-4       # 求解精度
    max_iterations: 100   # 最大迭代次数
    
  # 并行计算
  parallel:
    enabled: false       # 单智能体系统，不需要并行
    num_processes: 1      # 进程数量

# ============================================================
# 调试配置
# ============================================================
debug:
  enabled: true
  log_level: "INFO"
  log_file: "logs/local_control_config_2_1/debug.log"
  session_id: "local_control_config_2_1_session"
  
  # 数据收集
  data_collection:
    enabled: true
    interval: 100.0  # 数据收集间隔 (秒)
    variables:
      - "upstream_water_level"
      - "downstream_water_level"
      - "gate_opening"
      - "inflow_rate"
      - "pid_output"
      - "pid_error"
      - "pid_integral"
      - "pid_derivative"
      - "control_signal"
      - "sensor_noise"
      
  # Web仪表板
  dashboard:
    web_dashboard: true
    port: 8098
    auto_open: false
    
  # 控制台监控
  console:
    real_time_display: true
    update_interval: 100.0   # 实时监控控制状态
    show_detailed_logs: true
    show_pid_calculations: true

# ============================================================
# 性能监控配置
# ============================================================
performance:
  enabled: true
  
  # 时间跟踪
  timing:
    enabled: true
    detailed_profiling: true
    pid_timing: true
    control_loop_timing: true
    
  # 内存监控
  memory:
    enabled: true
    threshold_mb: 500   # 内存阈值
    
  # CPU监控
  cpu:
    enabled: true
    threshold_percent: 70  # CPU使用率警告阈值

# ============================================================
# 可视化配置
# ============================================================
visualization:
  enabled: true
  
  # 图表配置
  plots:
    enabled: true
    save_plots: true
    plot_directory: "plots/local_control_config_2_1/"
    format: "png"
    dpi: 300
    
    # 图表定义
    charts:
      - name: "水位控制响应"
        type: "time_series"
        variables: ["upstream_water_level", "target_level"]
        title: "Water Level Control Response"
        xlabel: "Time (seconds)"
        ylabel: "Water Level (m)"
        
      - name: "闸门开度控制"
        type: "time_series"
        variables: ["gate_opening"]
        title: "Gate Opening Control"
        xlabel: "Time (seconds)"
        ylabel: "Gate Opening (m)"
        
      - name: "PID控制信号"
        type: "time_series"
        variables: ["pid_output", "control_signal"]
        title: "PID Control Signal"
        xlabel: "Time (seconds)"
        ylabel: "Control Signal"
        
      - name: "PID误差分析"
        type: "time_series"
        variables: ["pid_error", "pid_integral", "pid_derivative"]
        title: "PID Error Analysis"
        xlabel: "Time (seconds)"
        ylabel: "Error Components"
        
      - name: "流量扰动"
        type: "time_series"
        variables: ["inflow_rate"]
        title: "Inflow Disturbance"
        xlabel: "Time (seconds)"
        ylabel: "Flow Rate (m³/s)"
        
      - name: "传感器噪声"
        type: "time_series"
        variables: ["sensor_noise"]
        title: "Sensor Noise"
        xlabel: "Time (seconds)"
        ylabel: "Noise Level"
        
  # 实时仪表板
  dashboard:
    enabled: true
    update_interval: 100.0   # 实时更新控制状态
    port: 8099

# ============================================================
# 数据输出配置
# ============================================================
output:
  enabled: true
  output_directory: "results/local_control_config_2_1/"
  
  # 历史数据保存
  save_history: true
  history_file: "simulation_history.json"
  
  # 数据格式
  format:
    csv: true
    json: true
    hdf5: false    # 单智能体系统数据量较小
    matlab: true   # 启用MATLAB格式用于控制分析
    
  # 压缩设置
  compression:
    enabled: false  # 数据量小，不需要压缩
    method: "gzip"
    
  # 验证配置
  validation:
    enabled: true
    expected_results:
      target_level: 4.0         # 目标水位 (m)
      tolerance: 0.1            # 容差 (m)
      steady_state_error: 0.05  # 稳态误差 (m)
      settling_time: 500.0      # 期望稳定时间 (秒)
    description: "系统应将上游水位稳定在PID设定点附近"

# ============================================================
# 智能分析配置
# ============================================================
analysis:
  enabled: true
  
  # 控制性能分析
  control_performance:
    enabled: true
    metrics: ["ise", "iae", "itae", "settling_time", "overshoot", "steady_state_error"]
    reference_tracking: true
    disturbance_rejection: true
    
  # 统计分析
  statistical:
    enabled: true
    generate_summary: true
    variance_analysis: true
    correlation_analysis: true
    
  # 系统识别
  system_identification:
    enabled: true
    method: "subspace"
    state_space_model: true
    input_signals: ["gate_opening"]
    output_signals: ["upstream_water_level"]
    
  # PID专用分析
  pid_analysis:
    enabled: true
    tuning_analysis: true
    stability_analysis: true
    robustness_analysis: true
    parameter_sensitivity: true
    
  # 闭环系统分析
  closed_loop_analysis:
    enabled: true
    step_response: true
    frequency_response: true
    stability_margins: true
    disturbance_response: true

# ============================================================
# 日志配置
# ============================================================
logging:
  enabled: true
  level: "INFO"
  
  # 文件日志
  file:
    enabled: true
    filename: "logs/local_control_config_2_1/simulation.log"
    max_size_mb: 20
    backup_count: 10
    
  # 控制台日志
  console:
    enabled: true
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
  # 结构化日志
  structured:
    enabled: true
    format: "json"
    
  # PID专用日志
  pid_log:
    enabled: true
    filename: "logs/local_control_config_2_1/pid.log"
    variables: ["pid_error", "pid_output", "pid_integral", "pid_derivative"]
    
  # 控制循环日志
  control_log:
    enabled: true
    filename: "logs/local_control_config_2_1/control.log"
    control_actions: true
    sensor_readings: true
    actuator_commands: true

# ============================================================
# 错误处理配置
# ============================================================
error_handling:
  enabled: true
  
  # 错误分类
  categories:
    critical: ["sensor_failure", "actuator_failure", "control_instability"]
    warning: ["sensor_noise_high", "actuator_saturation", "setpoint_deviation"]
    info: ["control_action", "sensor_reading", "normal_operation"]
    
  # 恢复策略
  recovery:
    auto_retry: true
    max_retries: 3
    retry_delay: 10.0
    fallback_controller: "manual_mode"
    
  # 通知设置
  notifications:
    enabled: true
    email: ["control_engineer@example.com"]
    webhook: "http://localhost:9000/control_alerts"

# ============================================================
# 缓存配置
# ============================================================
cache:
  enabled: true
  
  # 内存缓存
  memory:
    enabled: true
    max_size_mb: 100
    
  # 磁盘缓存
  disk:
    enabled: false  # 单智能体系统不需要磁盘缓存
    directory: "cache/local_control_config_2_1/"
    max_size_gb: 1

# ============================================================
# 网络配置
# ============================================================
network:
  enabled: true
  
  # 分布式仿真
  distributed:
    enabled: false  # 单智能体系统，不需要分布式
    master_host: "localhost"
    master_port: 9006
    
  # 通信设置
  communication:
    protocol: "tcp"
    timeout: 30
    buffer_size: 8192
    topics:
      upstream_level: "state/canal_upstream/level"
      gate_action: "action/gate/opening"
      inflow: "disturbance/inflow"

# ============================================================
# 安全配置
# ============================================================
security:
  enabled: true
  
  # 访问控制
  access_control:
    enabled: true
    allowed_hosts: ["localhost", "control-station"]
    
  # 加密设置
  encryption:
    enabled: false  # 本地仿真不需要加密
    algorithm: "AES-256"
    
  # 监控设置
  monitoring:
    enabled: true
    intrusion_detection: false
    safety_protocols: true

# ============================================================
# 扩展配置
# ============================================================
extensions:
  enabled: true
  
  # 插件系统
  plugins:
    enabled: true
    directory: "plugins/pid/"
    modules: ["adaptive_pid", "fuzzy_pid", "neural_pid"]
    
  # 自定义功能
  custom:
    enabled: true
    modules: ["advanced_tuning", "fault_detection", "performance_optimization"]

# ============================================================
# 环境配置
# ============================================================
environment:
  name: "development"
  
  # 环境变量
  variables:
    SIMULATION_ENV: "local_control_config_2_1"
    LOG_LEVEL: "INFO"
    CONTROL_MODE: "pid"
    
  # 自定义变量
  custom_vars:
    # 仿真参数
    description: "现地闭环控制系统演示"
    duration: 2000                # 仿真持续时间 (秒)
    dt: 10.0                      # 时间步长 (秒)
    
    # 通信主题
    upstream_level_topic: "state/canal_upstream/level"
    gate_action_topic: "action/gate/opening"
    inflow_topic: "disturbance/inflow"
    
    # 物理组件参数
    # 上游渠道
    upstream_canal_type: "UnifiedCanal"
    upstream_canal_model: "integral"
    upstream_initial_volume: 112100.0  # 对应约4.0m水位的体积
    upstream_bottom_width: 20.0
    upstream_length: 1000.0
    upstream_slope: 0.001
    upstream_side_slope_z: 2.0
    upstream_manning_n: 0.025
    
    # 下游渠道
    downstream_canal_type: "UnifiedCanal"
    downstream_canal_model: "integral"
    downstream_initial_volume: 50000
    downstream_bottom_width: 20.0
    downstream_length: 1000.0
    downstream_slope: 0.001
    downstream_side_slope_z: 2.0
    downstream_manning_n: 0.025
    
    # 控制闸门
    gate_type: "Gate"
    gate_initial_opening: 0.38    # 在设定点附近平衡入流的开度
    gate_discharge_coefficient: 0.8
    gate_width: 10.0
    gate_max_opening: 3.0
    gate_max_rate_of_change: 0.05
    
    # PID控制器参数
    pid_kp: -0.8                  # 比例增益
    pid_ki: -0.002                # 积分增益
    pid_kd: 0.0                   # 微分增益
    pid_setpoint: 4.0             # 目标水位 (米)
    pid_min_output: 0.0           # 最小输出
    pid_max_output: 3.0           # 最大输出（与闸门最大开度一致）
    
    # 智能体配置
    control_agent_id: "pid_agent_1"
    control_agent_dt: 10.0        # 控制周期 (秒)
    io_agent_id: "io_agent_1"
    
    # 传感器配置
    sensor_obj: "upstream_canal"
    sensor_state_key: "water_level"
    sensor_topic: "state/canal_upstream/level"
    sensor_noise_std: 0.01        # 传感器噪声标准差
    
    # 执行器配置
    actuator_obj: "control_gate"
    actuator_target_attr: "target_opening"
    actuator_topic: "action/gate/opening"
    actuator_control_key: "control_signal"
    
    # 扰动配置
    disturbance_agent_id: "inflow_disturbance_1"
    disturbance_topic: "disturbance/inflow"
    disturbance_start_time: 0
    disturbance_duration: 2000    # 整个仿真期间
    disturbance_inflow_rate: 15.0 # 流量 (m³/s)
    
    # 验证参数
    validation_target_level: 4.0  # 目标水位 (m)
    validation_tolerance: 0.1     # 容差 (m)
    validation_description: "系统应将上游水位稳定在PID设定点附近"
    
    # 调试参数
    debug_log_level: "INFO"
    debug_log_file: "example_2_1.log"
    debug_enable_performance_monitoring: true
    debug_enable_data_collection: true
    debug_data_collection_interval: 100
    debug_session_id: "example_2_1_session"
    
    # 控制性能参数
    expected_settling_time: 500.0     # 期望稳定时间 (秒)
    expected_overshoot: 10.0          # 期望超调量 (%)
    expected_steady_state_error: 0.05 # 期望稳态误差 (m)
    
    # 系统参数
    response_time: 100.0              # 系统响应时间 (秒)
    communication_delay: 1.0          # 通信延迟 (秒)
    sensor_accuracy: 0.01             # 传感器精度 (m)
    actuator_accuracy: 0.01           # 执行器精度 (m)