# 水箱PID出口控制 - 统一配置文件
# 重构后的水箱PID出口控制示例

simulation:
  name: "水箱PID出口控制"
  description: "重构后的水箱PID出口控制示例"
  duration: 300.0
  time_step: 1.0
  
components:
  watertank:
    type: "WaterTank"
    parameters:
      capacity: 1000.0
      initial_level: 80.0
      cross_sectional_area: 100.0
      target_level: 50.0
      constant_inflow: 20.0
  
  outlet_valve:
    type: "Valve"
    parameters:
      max_flow_rate: 60.0
      initial_opening: 0.3
    
control:
  enabled: true
  type: "PID"
  target_variable: "water_level"
  control_variable: "outlet_flow"
  parameters:
    kp: 1.5
    ki: 0.05
    kd: 0.8
    setpoint: 50.0
  
output:
  format: "json"
  save_path: "outlet_pid_results.json"
  variables:
    - "water_level"
    - "volume"
    - "outlet_flow"
    - "inflow"
    - "control_signal"
    - "error"