# 智能体控制智能体配置

# 感知智能体
reservoir_1_perception:
  type: "ReservoirPerceptionAgent"
  parameters:
    name: "主水库感知智能体"
    model_id: "reservoir_1"
    publish_topic: "reservoir_1/state"
    publish_interval: 1

reservoir_2_perception:
  type: "ReservoirPerceptionAgent"
  parameters:
    name: "下游水库感知智能体"
    model_id: "reservoir_2"
    publish_topic: "reservoir_2/state"
    publish_interval: 1

# 控制智能体
gate_control:
  type: "GateControlAgent"
  parameters:
    name: "闸门控制智能体"
    model_id: "gate_1"
    subscribe_topics: 
      - "reservoir_1/state"
      - "reservoir_2/state"
      - "central/command"
    control_strategy: "pid"
    pid_parameters:
      kp: 0.5
      ki: 0.1
      kd: 0.05

# 中央协调智能体
central_coordinator:
  type: "CentralDispatcherAgent"
  parameters:
    name: "中央协调智能体"
    subscribe_topics:
      - "reservoir_1/state"
      - "reservoir_2/state"
    publish_topic: "central/command"
    coordination_strategy: "level_balancing"
    target_level_difference: 5.0