# 智能体控制配置

simulation:
  duration: 24
  time_step: 1
  start_time: "2025-01-01 00:00:00"

components_file: "config/components.yml"
topology_file: "config/topology.yml"
agents_file: "config/agents.yml"

output:
  variables:
    - "reservoir_1.level"
    - "reservoir_2.level"
    - "gate_1.opening"
    - "agent_messages"
  format: "csv"
  directory: "results"